### PR TITLE
:notebook: Add README and example without pyqg

### PR DESCRIPTION
**Pull request by asross**
Addresses https://github.com/m2lines/EquationDisco/issues/10, https://github.com/m2lines/EquationDisco/issues/5, https://github.com/m2lines/EquationDisco/issues/9, and https://github.com/m2lines/EquationDisco/issues/6, superseding https://github.com/m2lines/EquationDisco/pull/11.

### CODE REVIEW

**Comment by dorchard** [comment]
Hi @asross - I found that just doing `import eqn_disco` wasn't working for me in the notebook because `eqn_disco` does not itself export the sub modules `util` etc. My solution is in this commit https://github.com/m2lines/EquationDisco/pull/15/commits/ef2fd0da618e4dbf1f22521883eff79aba4ca8db that way you can just do `import eqn_disco` as in your notebooks and get access to `eqn_disco.util...` etc. is that okay?

**Comment by dorchard** [comment]
@asross bump on the above - does my addition work okay for you?

**Comment by asross** [comment]
@dorchard Apologies for the late reply, just seeing this for some reason! Your change works for me 👍

**Comment by dorchard** [comment]
Okay that's great! There are a few other comments from me above. Can you take a look then I can approve.

**Comment by asross** [comment]
@dorchard not seeing the comments you mentioned above -- can you point me to them?

**Pull request merged**
