### PR TITLE
Code quality

### PR DESCRIPTION
**Pull request by jdenholm**
This pull request serves to address the items mentioned in issue #4 .

- [x] The addition of docstrings to all of the functions:
     - [x] utils.py
     - [x] hybrid_symbolic.py
- [x] The addition of type-hints to all functions:
     - [x] utils.py
     - [x] hybrid_symbolic.py
- [x] The application of pylint to all files:
     - [x] utils.py
     - [x] hybrid_symbolic.py
- [x] The application of black to all files:
     - [x] utils.py
     - [x] hybrid_symbolic.py
- [x] The application of pydocstyle—with the numpy convention—to all files:
     - [x] utils.py
     - [x] hybrid_symbolic.py

### CODE REVIEW

**Comment by jdenholm** [comment]
Hi @asross, do you think you could take a look at ``utils.py`` and help me with the TODOs, docstrings and variable names, please? I'd like the file to pass all of the checks I have mentioned in the first comment in this PR (where the check boxes are).

Hopefully everything is clear, but by all means give me a shout if not!

Cheers!

**Comment by jdenholm** [comment]
Also, ``hybrid_symbolic.py`` is ready for looking at, too! Give me a shout if you've any issues :)

**Comment by asross** [comment]
@jdenholm apologies for the delay, things have been crazy, but getting to this now!

**Comment by jdenholm** [comment]
@asross, no worries at all! 'Tis good to hear from you. There is no rush.

**Pull request merged**
